// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaRDChzQ_BIRrQw0klBFoffu-bfsD3Mfo',
    appId: '1:80343812189:web:f9b2c9e1785f13cf1aa5b4',
    messagingSenderId: '80343812189',
    projectId: 'e-commerce-c1b3f',
    authDomain: 'e-commerce-c1b3f.firebaseapp.com',
    storageBucket: 'e-commerce-c1b3f.firebasestorage.app',
    measurementId: 'G-83HBZC918G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZsp1X-KgSof0Sar-L7lOWvwqNbt_cw8A',
    appId: '1:80343812189:android:b5aca7a02958d5981aa5b4',
    messagingSenderId: '80343812189',
    projectId: 'e-commerce-c1b3f',
    storageBucket: 'e-commerce-c1b3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjHxA6TEFG5lYoYx-cfx5XeUQh_-wmx34',
    appId: '1:80343812189:ios:3d153810723574cf1aa5b4',
    messagingSenderId: '80343812189',
    projectId: 'e-commerce-c1b3f',
    storageBucket: 'e-commerce-c1b3f.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjHxA6TEFG5lYoYx-cfx5XeUQh_-wmx34',
    appId: '1:80343812189:ios:3d153810723574cf1aa5b4',
    messagingSenderId: '80343812189',
    projectId: 'e-commerce-c1b3f',
    storageBucket: 'e-commerce-c1b3f.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaRDChzQ_BIRrQw0klBFoffu-bfsD3Mfo',
    appId: '1:80343812189:web:027499a0f708f6061aa5b4',
    messagingSenderId: '80343812189',
    projectId: 'e-commerce-c1b3f',
    authDomain: 'e-commerce-c1b3f.firebaseapp.com',
    storageBucket: 'e-commerce-c1b3f.firebasestorage.app',
    measurementId: 'G-HTW7MPLCRG',
  );
}
